name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag gcr.io/graphic-fiber-394421/newebapp
   
    - name: Login to Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA }}'

    - name: Push to Google container Registry (GCR)
      run: |
        gcloud auth configure-docker
        docker push gcr.io/graphic-fiber-394421/newebapp

    - name: Deploy to CloudRun
      run: |
        gcloud run deploy newebapp --region europe-west1 --image cheph365/newebapp --platform managed --allow-unauthenticated --project graphic-fiber-394421